name: Node CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Test App
        run: node app.js

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login DockerHub
        run: echo "${{ secrets.123456789 }}" | docker login -u "${{ secrets.omshresth10 }}" --123456789-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.omshresth10 }}/api .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api